# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: Dental Solutions
description: Treatments include Veneers, Whitening, Implants, Cosmetic crowns, Straightening teeth, Denture stabilisation, Smile makeovers
url: helloiammichael.com
baseurl: /dental-solutions

contact:
  facebook: https://www.facebook.com/cosmeticdentist1/info/?section=hours&tab=page_info
  address: 23 Cherry Drive, Eglinton, BT47 3US
  tel: 02871811447
  tel_spaced: 028 7181 1447
  email: info@dentalsolutionsni.com
  directions: https://www.google.co.uk/maps/dir/''/23+Cherry+Dr,+Eglinton,+Londonderry,+Derry+BT47+3US/data=!4m5!4m4!1m0!1m2!1m1!1s0x48600942ce9610bd:0xa068bc53e821ec12?sa=X&ved=0ahUKEwjvjI-p0PfLAhXDQJoKHabwCPwQwwUIHjAA
  google: https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dental+solutions+ni&lrd=0x48600942cbe9c45d:0xef4243af857d5cf1,3,,

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Michael Mckeever
  email: mckeever02@gmail.com
  uri: www.helloiammichael.com
  bio: Front-end designer from Belfast
  twitter: mick_mckeever

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink:  none
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Settings for archives
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: 'year-archive'
    month: 'month-archive'
    category: 'category-archive'
    tag: 'tag-archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    category: '/category/:name/'
    tags: '/tag/:name/'

navigation:
  - title: Home
    url: /index.html
    id: home-link
  - title: Team
    url: /team.html
    id: team-link
  - title: Treatments
    url: /treatments.html
    id: treatments-link
  - title: Referring Dentists
    url: /referring-dentists.html
    id: referring-dentists-link
  - title: Testimonials
    url: /testimonials.html
    id: before-afters-link
  - title: Contact
    url: javascript:void(0)
    id: contact-link


sub_navigation:
  - title: Treatments
    url: treatments.html
  - title: Price Guide
    url: price-guide.html
  - title: Before & Afters
    url: before-afters.html#


collections:
  - testimonials
  - team
